### ISSUE TITLE
Use a gulp watch

### ISSUE THREAD

**Issue by mikehaas763** [lazd/gulp-karma#21]
Hi. I know you have just depended on using karma's builtin file-watching with this plugin thus far to keep it easy. I'm interested in getting it to use one of the gulp watch only plugins though. Either the built-in gulp.watch or the gulp-watch plugin.

A few reasons why I think this is important:
- Gulp's philosophy is using plugins that do one thing and do it really well.
- No need to have more than one watcher which I think would be good for performance.
- Grunt already does this.

I haven't even looked in to what this would take. In any case, would you be open to it?

**Comment by lazd** [comment]
`gulp-karma` is deprecated (#43). Please use Karma directly: https://github.com/karma-runner/gulp-karma
