### ISSUE TITLE
Advantages of this plugin?

### ISSUE THREAD

**Issue by marklagendijk** [lazd/gulp-karma#33]
What are the advantages of this plugin over [using Karma directly](https://github.com/karma-runner/gulp-karma)?
Also, doesn't this plugin violate the first rule of the [Gulp plugin guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md)?
> Your plugin should not do something that can be done easily with an existing node module
- For example: deleting a folder does not need to be a gulp plugin. Use a module like del within a task instead.
- Wrapping every possible thing just for the sake of wrapping it will pollute the ecosystem with low quality plugins that don't make sense within the gulp paradigm.
- gulp plugins are for file-based operations! If you find yourself shoehorning a complex process into streams just make a normal node module instead.
- A good example of a gulp plugin would be something like gulp-coffee. The coffee-script module does not work with Vinyl out of the box, so we wrap it to add this functionality and abstract away pain points to make it work well within gulp.

I kind of remember that there where some issues with using Karma directly, and I think that must be why I have been using this plugin. But since these issues are now fixed, is there still a reason for this plugin to exists?

**Comment by lazd** [comment]
`gulp-karma` is now formally deprecated (#43).
