### ISSUE TITLE
How to pass a regular expression in a karma configuration file?

### ISSUE THREAD

**Issue by mendlik** [lazd/gulp-karma#37]
Hi,

I am using webpack. My webpack configuration requires some regular expressions.
I cannot use regexes because karma config is stringified in [gulp-karma](https://github.com/lazd/gulp-karma/blob/master/index.js#L72) and than all regular expressions are converted into empty objects.

Is there any way to pass a regular expression in karma configuration using gulp-karma?

**Comment by lazd** [comment]
Hi @mendlik,
I'd recommend using Karma directly. `gulp-karma` has a number of shortcomings and this is definitely one of them. You may try checking out the [`helper` branch](https://github.com/lazd/gulp-karma/tree/helper) and see if that is more useful than `gulp-karma` in its current form.

The plan is to eventually refactor this module to be something more like the `helper` branch. Meanwhile, it's best to use Karma directly.

**Comment by mendlik** [comment]
Thanks @lazd 

I did as you suggested. I used karma directly and now regular expressions are preserved. Thanks.

My gulp task:
```javascript
gulp.task('test', function(done) {
	karmaServer.start(karmaConfig, function(exitCode) {
		gutil.log('Karma has exited with exit code: ', exitCode);
		if (exitCode) return done(new gutil.PluginError('Karma', 'Karma tests failed. Exit code: ' + exitCode));
		done();
	});
});
```
