### ISSUE TITLE
What's the point in giving .src() ?

### ISSUE THREAD

**Issue by garygreen** [lazd/gulp-karma#40]
Why does this plugin require src files to test when they are already specified in the karma conf -- that's the whole point of the conf. Just wondered the logic behind this...

**gulpfile.js**

```javascript
return gulp.src(testFiles)
    .pipe(karma({
      configFile: 'karma.conf.js',
      action: 'run'
    }))
```

**karma.conf.js**
```javascript
module.exports = function (config) {
  config.set({
    // base path, that will be used to resolve files and exclude
    basePath: '',

    frameworks: ['mocha', 'chai'],

    // list of files / patterns to load in the browser
    files: [
      'node_modules/jquery/dist/jquery.js',
      'jquery.my-lib.js',
      'test/*.js'
    ],
```

**Comment by lazd** [comment]
@garygreen it was done that way so it would be a valid gulp plugin (accepts a stream of files and does something with them). I also built gulp-karma to work around problems in Karma itself that are fixed now.

Now that Karma is in better shape, gulp-karma isn't really necessary any longer. I would suggest you use Karma directly: https://github.com/karma-runner/gulp-karma
