### ISSUE TITLE
Does not work with Karma 0.13.0

### ISSUE THREAD

**Issue by sbohan** [lazd/gulp-karma#42]
When trying to run this with newer version of karma, I receive the following error:

    /home/ubuntu/web-costa-de/node_modules/karma/lib/index.js:11
        throw new Error(
              ^
    Error: The api interface has changed. Please use 
      server = new Server(config, [done])
      server.start()

I can submit a PR if that helps but I see this project seems to have gone stale.

**Comment by jhare** [comment]
Also experiencing this issue. :point_right: :ok_hand:

**Comment by lazd** [comment]
Please use karma directly, with the new APIs, gulp-karma is no longer needed.

https://github.com/karma-runner/gulp-karma

**Comment by jhare** [comment]
Let's deprecate this module so newcomers know to go do that. Updating our build tasks here as well. Thanks!

https://docs.npmjs.com/cli/deprecate

**Comment by the-simian** [comment]
references #43

**Comment by lazd** [comment]
@jhare sounds like a plan.
