### ISSUE TITLE
Formally deprecate gulp-karma

### ISSUE THREAD

**Issue by jhare** [lazd/gulp-karma#43]
Creating separate issue to track progress on deprecating this module in favor of running karma directly.

https://docs.npmjs.com/cli/deprecate

From the karma folks:
```js
var gulp = require('gulp');
var Server = require('karma').Server;

/**
 * Run test once and exit
 */
gulp.task('test', function (done) {
  new Server({
    configFile: __dirname + '/karma.conf.js',
    singleRun: true
  }, done).start();
});
```

**Comment by deltaidea** [comment]
:+1:

**Comment by lazd** [comment]
`gulp-karma` has been formally deprecated with the following message:

```
npm WARN deprecated gulp-karma@0.0.4: Please use Karma directly: https://github.com/karma-runner/gulp-karma
```

**Comment by AnatoliyLitinskiy** [comment]
Hi.

You've closed this ticked but not answered the main question
"how to install karma using npm and avoid warning message?"

There is nothing about installing your packange using gulp in your documentation

https://github.com/lazd/gulp-karma/issues/42

https://github.com/lazd/gulp-karma/issues/45

**Comment by lazd** [comment]
@AnatoliyLitinskiy This package is deprecated and no longer unsupported.

See https://github.com/karma-runner/gulp-karma

**Comment by jimmywarting** [comment]
Should also deprecate the npm package and also archive this repo
