### ISSUE TITLE
Pulling file list from karma.conf.js

### ISSUE THREAD

**Issue by nathasm** [lazd/gulp-karma#9]
I've been trying to figure out a way to use my existing karma.conf.js file that already has a list of the test files.

Is there a way to pull the files property from the karma.conf.js file without having to put the file list in my gulp.js file?

**Comment by broekema41** [comment]
Hello drkibitz and lazd, I was struggling with the fixtures issue mentioned above.
As a quick fix I decided to add them to the options object 
![image](https://cloud.githubusercontent.com/assets/4007585/6984411/d99e43c4-da28-11e4-9870-b1b99491680c.png)
Then included them later in the gulp-karma index.js "endStream" function
![image](https://cloud.githubusercontent.com/assets/4007585/6984435/2682c3fe-da29-11e4-967a-a375eb20f5cd.png)

Hoping this prevent others searching for a way to include non js files

**Comment by lazd** [comment]
`gulp-karma` is deprecated (#43). Please use Karma directly: https://github.com/karma-runner/gulp-karma
